
server:
  port: 8081


spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 118.178.105.210:8848

dubbo:
  scan:
    base-packages: com.alibaba.service.impl
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://118.178.105.210

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

